substitutions:
  devicename: skyfan-bedroom1

esphome:
  name: $devicename

esp8266:
  board: esp12e

# Enable logging disable as using serial
logger:
  baud_rate: 0

web_server:
  port: 80

api:

ota:
  password: !secret esp_home_ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

i2c:
  sda: 4
  scl: 5
  scan: True

sensor:
  - platform: bme280
    temperature:
      name: "Bedroom1 BME280 Temp"
      oversampling: 16x
    pressure:
      name: "Bedroom1 BME280 Pressure"
    humidity:
      name: "Bedroom1 BME280 Humidity"
    address: 0x76
    update_interval: 60s

tuya:

fan:
  - platform: tuya
    name: Bedroom1 Fan
    id: bedroom1_fan
    switch_datapoint: 1
    direction_datapoint: 8

number:
  - platform: "tuya"
    name: Fan Speed
    number_datapoint: 3
    min_value: 0
    max_value: 5
    step: 1

mqtt:
  broker: !secret mqtt_broker
  on_message:
    - topic: $devicename/fan/bedroom1_fan/cmd
      payload: "ON"
      then:
      - fan.turn_on: bedroom1_fan
    - topic: $devicename/fan/bedroom1_fan/cmd
      payload: "OFF"
      then:
      - fan.turn_off: bedroom1_fan
    - topic: $devicename/fan/bedroom1_fan/cmd
      payload: "TOGGLE"
      then:
      - fan.toggle: bedroom1_fan






